[package]
name = "mem_usage_benches"
version.workspace = true
edition.workspace = true

[dependencies]
bouncycastle.workspace = true


[[bin]]
name = "bench_mldsa_mem_usage"
path = "bench_mldsa_mem_usage.rs"

[[bin]]
name = "bench_mlkem_mem_usage"
path = "bench_mlkem_mem_usage.rs"

[[bin]]
name = "bench_sha3_mem_usage"
path = "bench_sha3_mem_usage.rs"
