//! Known-answer vector tests. The vectors in `vectors_data.rs` are committed,
//! generated by `dev_scripts/gen_bigint_vectors.py` with Python's unbounded
//! integers as the independent oracle (see the file header for regeneration).

use crate::bigint::limb::Limb;
use crate::bigint::uint::Uint;

include!("vectors_data.rs");

/// 256-bit capacity under either limb width; matches the vector limb arrays.
type U256 = Uint<{ 256 / crate::bigint::limb::WORD_BITS }>;

#[test]
fn adc_vectors() {
    for &(a, b, carry, sum, carry_out) in data::ADC {
        let (s, c) = Limb(a).adc(Limb(b), Limb(carry));
        assert_eq!((s.0, c.0), (sum, carry_out));
    }
}

#[test]
fn sbb_vectors() {
    for &(a, b, borrow_in, diff, borrow_out) in data::SBB {
        let (d, bo) = Limb(a).sbb(Limb(b), Limb(borrow_in));
        assert_eq!((d.0, bo.0), (diff, borrow_out));
    }
}

#[test]
fn mac_vectors() {
    for &(acc, b, c, carry, lo, hi) in data::MAC {
        let (l, h) = Limb(acc).mac(Limb(b), Limb(c), Limb(carry));
        assert_eq!((l.0, h.0), (lo, hi));
    }
}

#[test]
fn be256_vectors() {
    for (bytes, limbs) in data::BE256 {
        let x = U256::from_be_bytes(bytes);
        for (i, &expected) in limbs.iter().enumerate() {
            assert_eq!(x.limb(i).0, expected);
        }
        let back: [u8; 32] = x.to_be_bytes();
        assert_eq!(&back, bytes);
    }
}

#[test]
fn ragged_vectors() {
    for (bytes, limbs) in data::RAGGED {
        // unwrap justification: every RAGGED vector length is <= the 32-byte
        // capacity by construction (see RAGGED_LENS in the generator).
        let x = U256::from_be_slice(bytes).unwrap();
        for (i, &expected) in limbs.iter().enumerate() {
            assert_eq!(x.limb(i).0, expected);
        }
    }
}
